info:
  contact: {}
paths:
  /user/list:
    get:
      consumes:
      - application/json
      description: Get the API's user list
      produces:
      - application/json
      responses: {}
      summary: User list endpoint
      tags:
      - admin
swagger: "2.0"
